services:
  - type: web
    name: my-analytics
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        value: postgresql://postgres.gxuboxbydihumjxzafiz:7KaJCJUguGMw2rTN@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
      - key: WEB_CONCURRENCY
        value: 4