# Generated by Django 5.1.7 on 2025-03-16 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.IntegerField()),
                ('videoTitle', models.CharField(max_length=100)),
                ('get_at', models.DateField(default=django.utils.timezone.now)),
                ('YouTubeView', models.PositiveIntegerField()),
                ('niconicoView', models.PositiveIntegerField()),
                ('YouTubeLike', models.PositiveIntegerField()),
                ('niconicoLike', models.PositiveIntegerField()),
                ('YouTubeComment', models.PositiveIntegerField()),
                ('niconicoComment', models.PositiveIntegerField()),
                ('niconicoMylist', models.PositiveIntegerField()),
            ],
        ),
    ]
