# Generated by Django 5.1.7 on 2025-03-22 01:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_number', models.IntegerField(unique=True)),
                ('title', models.CharField(default='title', max_length=100)),
                ('posted_at', models.DateField()),
                ('YouTube', models.CharField(blank=True, max_length=11, null=True)),
                ('niconico', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('get_at', models.DateField(default=django.utils.timezone.now)),
                ('YouTubeView', models.PositiveIntegerField()),
                ('niconicoView', models.PositiveIntegerField()),
                ('YouTubeLike', models.PositiveIntegerField()),
                ('niconicoLike', models.PositiveIntegerField()),
                ('YouTubeComment', models.PositiveIntegerField()),
                ('niconicoComment', models.PositiveIntegerField()),
                ('niconicoMylist', models.PositiveIntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.video')),
            ],
        ),
    ]
