# Generated by Django 5.1.7 on 2025-03-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='videoTitle',
        ),
    ]
