# Generated by Django 5.1.7 on 2025-03-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='YouTubeComment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='YouTubeLike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='YouTubeView',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='niconicoComment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='niconicoLike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='niconicoMylist',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='niconicoView',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
