name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Set Environment Variables
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SUPABASE_WEB_URL: ${{ secrets.SUPABASE_WEB_URL }}
        SUPABASE_WEB_KEY: ${{ secrets.SUPABASE_WEB_KEY }}
        SUPABASE_ANALYTIC_USER: ${{ secrets.SUPABASE_ANALYTIC_USER }}
        SUPABASE_ANALYTIC_URL: ${{ secrets.SUPABASE_ANALYTIC_URL }}
        SUPABASE_ANALYTIC_KEY: ${{ secrets.SUPABASE_ANALYTIC_KEY }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
      run: echo "Environment variables have been set"
    - name: Lint with flake8
      run: |
        #stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        #exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SUPABASE_WEB_URL: ${{ secrets.SUPABASE_WEB_URL }}
        SUPABASE_WEB_KEY: ${{ secrets.SUPABASE_WEB_KEY }}
        SUPABASE_ANALYTIC_USER: ${{ secrets.SUPABASE_ANALYTIC_USER }}
        SUPABASE_ANALYTIC_URL: ${{ secrets.SUPABASE_ANALYTIC_URL }}
        SUPABASE_ANALYTIC_KEY: ${{ secrets.SUPABASE_ANALYTIC_KEY }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}
      run: |
        python manage.py test
